version: '3.8'

services:
  # 1. SİZİN API PROJENİZ
  moneytransfercenter.webapi:
    image: ${DOCKER_REGISTRY-}moneytransfercenterwebapi
    build:
      context: .
      dockerfile: Src/MoneyTransferCenter.WebAPI/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=db_sqlserver;Database=MoneyTransferCenterDb;User Id=sa;Password=Guc1u_Sifre.123;TrustServerCertificate=true
      - MongoDB__ConnectionString=mongodb://db_mongodb:27017
      - Jaeger__Endpoint=http://jaeger:4317
    depends_on:
      - db_sqlserver
      - db_mongodb
      - jaeger

  # 2. MICROSOFT SQL SERVER
  db_sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Guc1u_Sifre.123
    ports:
      - "1433:1433"

  # 3. MONGODB
  db_mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  # 4. JAEGER OPENTELEMETRY
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Arayüz portu
      - "4317:4317"   # Log toplama portu


  # 5. PROMETHEUS — Metric Deposu
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      # API'nin nerede olduğunu Prometheus'a söyleyen ayar dosyası
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - moneytransfercenter.webapi

  # 6. GRAFANA — Dashboard
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
  # 7. LOKI — Log Deposu
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
